Consultoria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ConsultoriaApp.urls')),
    path('pago/', include('pago.urls', namespace="pago")),
    path('user/', include('accounts.urls', namespace="user")),
    ]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

ConsultoriaApp/urls.py
from django.urls import path
from ConsultoriaApp import views


urlpatterns = [
    #Menu
    path('',views.inicio, name="Inicio"),
    path('¿Quienes-somos?',views.conocenos, name="Conocenos"),
    path('Contacto',views.contacto, name="Contacto"),

    #Login
    path('Inicio-de-sesion',views.inicios, name="index"),
    path('Registro',views.registro, name="registro"),
    path('signout/',views.cierres, name='signout'),

    #Servicios
    path('1-Tramites-Registros-y-Autorizaciones',views.tramites, name="Tramites"),
    path('2-Auditoria-Preventiva',views.auditoria, name="Auditoria"),
    path('3-Atencion-de-Auditorias',views.atencion, name="Atencion"),
    path('4-Asistencia-Legal',views.asistencia, name="Asistencia"),
    path('5-Asistencia-en-la-Operacion-Aduanera',views.asistenciaOA, name="AsistenciaOA"),
    path('6-Capacitacion',views.capacitacion, name="Capacitacion"),
    path('7-Estrategias-Comerciales',views.estrategias, name="Estrategias"),
    path('8-Servicios-Corporativas',views.serviciosC, name="ServiciosC"),
    path('9-Servicios-Digitales',views.serviciosD, name="ServiciosD"),
    path('10-Alianzas-Estrategicas',views.alianzas1, name="Alianzas1"),
    path('10.2-Alianzas-Estrategicas',views.alianzas2, name="Alianzas2"),
    path('10.3-Alianzas-Estrategicas',views.alianzas3, name="Alianzas3"),

    #Videos
    path('Tramites-Registros-y-Autorizaciones',views.tramitesvideo, name="TramiteVideo"),
    path('Auditoria-Preventiva',views.auditoriavideo, name="auditoriaVideo"),
    path('Atencion-de-Auditorias',views.atenciónvideo, name="auditoriaVideo"),
    path('Asistencia-Legal',views.asistenciavideo, name="asitenciavideo"),
    path('Asistencia-en-la-Operacion-Aduanera',views.aoavideo, name="aoavideo"),
    path('Capacitacion',views.capacitacionvideo, name="capacitacionvideo"),
    path('Estrategias-Comerciales',views.estrategiasvideo, name="estrategiasvideo"),
    path('Servicios-Corporativas',views.servicioscvideo, name="servicioscvideo"),
    path('Servicios-Digitales',views.serviciosdvideo, name="serviciosdvideo"),
    path('Alianzas-Estrategicas',views.ae1video, name="ae1video"),
    path('Alianzas-Estrategicas-2',views.ae2video, name="ae2video"),
    path('Alianzas-Estrategicas-3',views.ae3video, name="ae3video"),
]

pago/urls.py
from django.urls import path

from .views import ChangeSubscriptionView, CreateSubscriptionView, PaymentView, PricingView, RetryInvoiceView, ThankYouView, send_invoice, webhook

app_name="pago"

urlpatterns = [
    path('pricing/', PricingView.as_view(), name="pricing"),
    path('checkout/<slug>/', PaymentView.as_view(), name="checkout"),
    path('create-subscription/', CreateSubscriptionView.as_view(), name='create-subscription'),
    path('thank-you/',ThankYouView.as_view(),name='thank-you'),
    path('retry-invoice/', RetryInvoiceView.as_view(), name='retry-invoice'),
    path('webhook/', webhook, name='webhook'),
    path('change-subscription/', ChangeSubscriptionView.as_view(), name='change-subscription'),
    path('send-invoice/<str:invoice_id>/', send_invoice, name='send-invoice')
]

ConsultoriaApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
User = get_user_model()


class UserCreationFormWithEmail(UserCreationForm):
    """
    Formulario que incluye campos adicionales como el correo electrónico, 
    el nombre y el apellido de los usuarios (ya que en el formulario por 
    defecto la clase "UserCreationForm" la cual solo registra usuario y contraseña).

    Atributos:
    - email (EmailField): Campo de correo electrónico requerido.
    - first_name (CharField): Campo de nombre del usuario.
    - last_name (CharField): Campo de apellido del usuario.
    """
    email = forms.EmailField(max_length=254, help_text='Se requiere información valida del correo.')
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30) 

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

ConsultoriaApp/views.py
from django.conf import settings
from .models import Pricing, Subscription, Cursos 
from .forms import UserCreationFormWithEmail
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

import stripe

#llave secreta de Stripe
stripe.api_key = settings.STRIPE_SECRET_KEY

#Interfaces de Menu
def inicio(request):
    """ Renderiza el archivo de inicio.html """
    return render(request, 'ConsultoriaApp/inicio.html')

def conocenos(request):
    """ Renderiza el archivo de Conocenos.html """
    return render(request, 'ConsultoriaApp/Conocenos.html')

def contacto(request):
    """Renderiza el archivo de contacto.html"""
    return render(request, 'ConsultoriaApp/Contacto.html')

#Interfaces del Login
def registro(request, *args, **kwargs):
    """ Maneja el registro de usuarios. Crea una cuenta de usuario y una suscripción de 
    prueba gratuita en Stripe."""
    if request.method == 'POST':
        form = UserCreationFormWithEmail(request.POST)
        if form.is_valid():
            # Registra al usuario
            user = form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            # Autentica al usuario
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            # Crea un cliente de Stripe asociado al nuevo usuario
            free_trial_pricing = Pricing.objects.get(name='Free Trial')

            subscription = Subscription.objects.create(
                user=user,
                pricing=free_trial_pricing
            )
            # Crear cliente de Stripe
            stripe_customer = stripe.Customer.create(
                email=user.email,
                name=user.username
            )
            # Crear suscripción en Stripe con un periodo de prueba de 7 días
            stripe_subscription = stripe.Subscription.create(
                customer=stripe_customer.id,
                items=[{'price': 'price_1PH8wPJmTTplu4eg3XFPNqWJ'}],
                trial_period_days=7
            )
            # Actualizar la suscripción y el usuario con detalles de Stripe
            subscription.status=stripe_subscription.status
            subscription.stripe_subscription_id = stripe_subscription.id
            subscription.save()
            user.stripe_customer_id = stripe_customer.id
            user.save()
            # Redirigir a la página principal después de un registro exitoso
            return redirect('/')
    else:
         # Si no es una solicitud POST, mostrar el formulario de registro
        form = UserCreationFormWithEmail()
        # Renderizar la página de registro.html con el formulario
    return render(request, 'ConsultoriaApp/Login/registro.html', {'form': form})

def inicios(request):
    """ Maneja el inicio de sesión de los usuarios. Si el usuario ya está autenticado, 
    lo redirige a la página de inicio. En dado caso de que no sea asi, procesa el formulario 
    de inicio de sesión. 
    """
    # Verifica si el usuario ya está autenticado
    if request.user.is_authenticated:
        # Si el usuario está autenticado, renderiza la página de inicio
        return render(request, 'ConsultoriaApp/inicio.html')
    # Verifica si el método de la solicitud es POST
    if request.method == 'POST':
         # Obtiene el nombre de usuario y la contraseña del formulario de inicio de sesión
        username = request.POST['username']
        password = request.POST['password']
        # Autentica al usuario con las credenciales proporcionadas
        user = authenticate(request, username=username, password=password)
        # Si las credenciales son correctas y el usuario existe
        if user is not None:
            # Inicia sesión del usuario
            login(request, user)
            # Redirige a la página de inicio
            return redirect('/')
        else:
            # Si las credenciales son incorrectas, muestra un mensaje de error
            msg = 'Error Login'
            form = AuthenticationForm(request.POST)
            return render(request, 'ConsultoriaApp/Login/index.html', {'form': form, 'msg': msg})
    else:
        # Si el método de la solicitud no es POST, muestra el formulario de inicio de sesión
        form = AuthenticationForm()
        return render(request, 'ConsultoriaApp/Login/index.html', {'form': form})   
    
def cierres(request):
    """ Maneja el cierre de Sesion del usuario. Una vez que el usuario realiza la acción de logout
    se redirige a la página de inicio """
    # Cierra la sesión del usuario
    logout(request)
    # Redirige a la página de inicio
    return redirect('/')   

#Interfaces de los Servicios
def tramites(request):
    """ renderiza el archivo 1tramies.html """
    return render(request, 'ConsultoriaApp/Servicios/1tramites.html')

def auditoria(request):
    """ renderiza el archivo 2Auditoría Preventiva.html """
    return render(request, 'ConsultoriaApp/Servicios/2Auditoría Preventiva.html')

def atencion(request):
    """ renderiza el archivo 3Atención.html """
    return render(request, 'ConsultoriaApp/Servicios/3Atención.html')

def asistencia(request):
    """ renderiza el archivo 4Asistencia.html """
    return render(request, 'ConsultoriaApp/Servicios/4Asistencia.html')

def asistenciaOA(request):
    """ renderiza el archivo 5Asistencia en la Operación Aduanera.html """
    return render(request, 'ConsultoriaApp/Servicios/5Asistencia en la Operación Aduanera.html')

def capacitacion(request):
    """ renderiza el archivo 6Capacitación.html """
    return render(request, 'ConsultoriaApp/Servicios/6Capacitación.html')

def estrategias(request):
    """ renderiza el archivo 7Estrategias Comerciales.html """
    return render(request, 'ConsultoriaApp/Servicios/7Estrategias Comerciales.html')

def serviciosC(request):
    """ renderiza el archivo 8Servicios Corporativos.html """
    return render(request, 'ConsultoriaApp/Servicios/8Servicios Corporativos.html')

def serviciosD(request):
    """ renderiza el archivo 9Servicios Digitales.html """
    return render(request, 'ConsultoriaApp/Servicios/9Servicios Digitales.html')

def alianzas1(request):
    """ renderiza el archivo 10.1Alianzas Estratégicas Submenú1 (Servicios Especializados).html """
    return render(request, 'ConsultoriaApp/Servicios/10.1Alianzas Estratégicas Submenú1 (Servicios Especializados).html')

def alianzas2(request):
    """ renderiza el archivo 10.2Alianzas Estratégicas Submenú2 (Servicios Tercerizados).html """
    return render(request, 'ConsultoriaApp/Servicios/10.2Alianzas Estratégicas Submenú2 (Servicios Tercerizados).html')

def alianzas3(request):
    """ renderiza el archivo 10.3Alianzas Estratégicas Submenú3 (Servicios Tercerizados).html """
    return render(request, 'ConsultoriaApp/Servicios/10.3Alianzas Estratégicas Submenú3 (Servicios Tercerizados).html')

#Funcion para dar permiso de ver el curso si tiene la suscripcion activa

def permission_subscription(user, course_name):
    """
    Verifica si un usuario tiene permiso para acceder a cursos basados en su suscripción.
    """
    # Filtra los cursos por el nombre del curso especificado
    courses = Cursos.objects.filter(course_name=course_name)
    # Filtra las suscripciones activas del usuario
    subscriptions = user.subscriptions.filter(status='active')
    # Si no hay suscripciones activas, devuelve una lista vacía
    if not subscriptions:
        return []
    # Obtiene los precios de las suscripciones activas
    pricing_tiers = [sub.pricing for sub in subscriptions]
    # Filtra los cursos a través del pricing de la suscripción
    return [
        course for course in courses 
        if any(pricing_tier in course.pricing_tiers.all() for pricing_tier in pricing_tiers)
    ]

# Interfaces donde se mostraran los Videos
@login_required
def tramitesvideo(request, *args, **kwargs):
    """
    Se renderiza la página de Tramites.html, mostrando solo 
    los cursos que el usuario tiene permiso de poder acceder. 
    """
    # Obtiene los cursos a los que el usuario tiene permiso de acceder
    courses = permission_subscription(request.user, 'Tramites, Registros y Autorizaciones')
    # Renderiza la página con los cursos filtrados
    return render(request, 'ConsultoriaApp/ServiciosVideos/Tramites.html', {'courses': courses})

@login_required
def auditoriavideo(request, *args, **kwargs):
    """
    Se renderiza la página de 2Auditoria.html, mostrando solo 
    los cursos que el usuario tiene permiso de poder acceder. 
    """
    courses = permission_subscription(request.user, 'Auditoría Preventiva')
    return render(request, 'ConsultoriaApp/ServiciosVideos/2Auditoria.html', {'courses': courses})

@login_required
def atenciónvideo(request, *args, **kwargs):
    """
    Se renderiza la página de 3Atencion.html, mostrando solo 
    los cursos que el usuario tiene permiso de poder acceder. 
    """
    courses = permission_subscription(request.user, 'Atención de Auditorías')
    return render(request, 'ConsultoriaApp/ServiciosVideos/3Atencion.html', {'courses': courses})

@login_required
def asistenciavideo(request, *args, **kwargs):
    """
    Se renderiza la página de 4Asistencia.html, mostrando solo 
    los cursos que el usuario tiene permiso de poder acceder. 
    """
    courses = permission_subscription(request.user, 'Asistencia legal')
    return render(request, 'ConsultoriaApp/ServiciosVideos/4Asistencia.html', {'courses': courses})

@login_required
def aoavideo(request, *args, **kwargs):
    """
    Se renderiza la página de 5AOA.html, mostrando solo 
    los cursos que el usuario tiene permiso de poder acceder. 
    """
    courses = permission_subscription(request.user, 'Asistencia en la operación aduanera')

ConsultoriaApp/templates/ConsultoriaApp/Conocenos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>¿Quiénes Somos?</title>
    {% load static %}

    <title>Consultoria</title>
          <meta charset="utf-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
  
      <!-- Bootstrap -->
      <link href="{% static 'ConsultoriaApp/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  
       <!-- Fonts -->
      
       <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet"> 
       <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
       <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,800,800italic" rel="stylesheet">
       
  
      <!-- Styles -->
      <link href="{% static 'ConsultoriaApp/css/Estilo.css' %}" rel="stylesheet">
      <noscript><link href="{% static 'ConsultoriaApp/css/noscript.css' %}" rel="stylesheet"></noscript>
  
</head>
<body>

    <main>
        <a href="#" class="boton-regreso" onclick="goBack()">&larr; Regresar</a>

        <script>
            function goBack() {
                window.history.back();
            }
        </script>

        <style>
            .boton-regreso {
            position: absolute;
            top: 10px;
            left: 10px;
            padding: 10px 20px;
            font-size: 16px;
            text-decoration: none;
            color: #fff;
            background-color: #3498db;
            border-radius: 5px;
            transition: background-color 0.3s;
            }

            .boton-regreso:hover {
                background-color: #2980b9;
            }
            
        </style>


        <div class="contenedor__todo">
            <div class="caja__trasera">
                <div class="caja__trasera-loguin">
                    <h1 style="font-size: 30px; text-align: center; color: #fff; font-family: arial;">Quienes somos</h1>
                    <p style="font-size: 23px; text-align: justify ; color: #fff;">
                        Somos una empresa 100% orgullosamente mexicana, dedicada a 
                        brindar asesorías en el área fiscal, así como en temas en 
                        comercio exterior y cfdis
                    </p>
                    <br>
                    <h1 style="font-size: 30px; text-align: center; color: #fff; font-family: arial;">Nuestra misión</h1>
                    <p style="font-size: 23px; text-align: justify; color: #fff;">
                    es poder resolver las dudas de nuestros clientes asesorándolos
                    de una manera profesional y correctamente para su mejor desempeño 
                    y evolución, a través de un servicio eficiente y de la mejor
                    calidad, siempre cuidando los procesos y la transparencia, 
                    que correspondan con las leyes así como con los lineamientos 
                    internos de nuestra empresa.
                    
                </p>
            </br>
            <br>
            <h1 style="font-size: 30px; text-align: center; color: #fff; font-family: arial;">Nuestros valores</h1>
                    <p style="font-size: 23px; text-align: justify  ; color: #fff;">
                    Honestidad: 
                    Asegurarnos de que nuestras asesorías cuenten con especialistas 
                    100% acorde a la materia que se requiera.
                </p>
                <p style="font-size: 23px; text-align: justify ; color: #fff;">
                    Transparencia:
                    Nuestros servicios cuentan con la integridad y discreción de los 
                    colaboradores, además de ser un servicio de alta calidad.
                    </p>
                    <p style="font-size: 23px; text-align: justify ; color: #fff;">
                    Innovación: Estamos a la vanguardia en información y en el aspecto 
                    regulatorio y técnico que el SAT brinda a sus contribuyentes.
                </p>
            </br>
        </div>
    </div>
</div>
    </main>
</body>
</html>

ConsultoriaApp/templates/ConsultoriaApp/Contacto.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Trámites, Registros y Autorizaciones</title>
    {% load static %}
  
      <!-- Bootstrap -->
      <link href="{% static 'ConsultoriaApp/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  
       <!-- Fonts -->
      
       <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet"> 
       <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
       <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,800,800italic" rel="stylesheet">
       
  
      <!-- Styles -->
      <link href="{% static 'ConsultoriaApp/css/gestion2.css' %}" rel="stylesheet">
      <noscript><link href="{% static 'ConsultoriaApp/css/noscript.css' %}" rel="stylesheet"></noscript>
  
    <style>
        body, h1, p {
            font-family: 'Arial', sans-serif;
        }
    
       
       
			/* Estilo para el enlace de WhatsApp */
			#whatsapp-link {
				position: fixed;
				bottom: 10px;
				left: 10px;
				backdrop-filter: blur(30px);
				background-color:  #25d366;

				color: #fff;
				padding: 10px;
				text-decoration: none;
				border-radius: 5px;
			}

			/* Estilo para los enlaces de redes sociales */
			#social-links {
				position: fixed;
				bottom: 10px;
				left: 50%;
				transform: translateX(-50%);
			}

			#social-links a {
				margin: 0 10px;
				text-decoration: none;
			}
    </style>
</head>
<body>
    <main>
        <a href="#" class="boton-regreso" onclick="goBack()">&larr; Regresar</a>

        <script>
            function goBack() {
                window.history.back();
            }
        </script>
        
        <div class="contenedor__todo">
            <div class="caja__trasera">
                <div class="caja__trasera-loguin">
                <p style=" color: #fff;">
                    <h1 style="font-size: 30px; text-align: center; color: #fff; font-family: arial;">
                        Contacto
                    </h1>
                </p>
                    <br></br>
                    <p style="font-size: 23px; text-align: justify ; color: #fff;">
                        
                        <br>Email: </br>
                        <br>Telefono: </br>
                        <br>Ubucacion: </br>
                        <br>Redes Sociales:</br>
                        
                    </p>
                </div>
            </div>
        </div>
        <main>
            <!-- Tu contenido principal aquí -->
        </main>
       
    
        <a id="whatsapp-link" href="https://api.whatsapp.com/send?phone=5612022454" target="_blank">Contacto de WhatsApp</a>
</body>
</html>

ConsultoriaApp/templates/ConsultoriaApp/inicio.html
<!DOCTYPE HTML>
<html lang="en" dir="ltr">

<head>
  {% load static %}

  <title>Consultoria</title>
  <meta charset="utf-8" />
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

  <!-- Bootstrap -->
  <link href="{% static 'ConsultoriaApp/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Fonts -->

  <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,800,800italic"
    rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!-- Boxicons CDN Link -->
  <link href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" rel="stylesheet" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Styles -->
  <link href="{% static 'ConsultoriaApp/css/gestion1.css' %}" rel="stylesheet">
  <noscript>
    <link href="{% static 'ConsultoriaApp/css/noscript.css' %}" rel="stylesheet">
  </noscript>

  <style>
    /* Estilo para el enlace de WhatsApp */
    #whatsapp-link {
      position: fixed;
      bottom: 10px;
      left: 10px;
      backdrop-filter: blur(30px);
      background-color: #25d366;

      color: #fff;
      padding: 10px;
      text-decoration: none;
      border-radius: 5px;
    }

    /* Estilo para los enlaces de redes sociales */
    #social-links {
      position: fixed;
      bottom: 10px;
      left: 50%;
      transform: translateX(-50%);
    }

    #social-links a {
      margin: 0 10px;
      text-decoration: none;
    }

    /* Estilo para ocultar el submenú por defecto */
    #menu ul ul {
      display: none;
    }
  </style>
</head>

<body class="landing is-preload">



  <!-- Page Wrapper -->
  <div id="page-wrapper">

    <!-- Header -->
    <header id="header" class="alt">
      <h1><a href="{% url 'Inicio' %}"> Proyecto Consultoria</a></h1>
      <nav id="nav">
        <ul>
          <li class="special">
            {% block content %}
            {% if user.is_authenticated %}
            Hola {{ user.username }}!
            <a href="/signout" class="btn btn-danger">Cerrar Sesión</a>
            <a href="{% url 'pago:pricing' %}" class="btn btn-danger">Precios</a>
            {% else %}
            <a href="/Inicio-de-sesion" class="btn btn-danger"><span>Iniciar Sesión</span></a>
            {% endif %}
            
            {% if user.is_superuser %}
            <a href="/admin" class="btn btn-danger">editar</a>
            {% else %}

            {% endif %}
            {% endblock %}
            <div id="menu">
              <ul>
                <li><a>Servicios</a></li>
                <li><a href="{% url 'Tramites' %}">1 Tramites, Registros y Autorizaciones</a></li>
                <li><a href="{% url 'Auditoria' %}">2 Auditoría Preventiva</a></li>
                <li><a href="{% url 'Atencion' %}">3 Atención de Auditorías</a></li>
                <li><a href="{% url 'Asistencia' %}">4 Asistencia legal</a></li>
                <li><a href="{% url 'AsistenciaOA' %}">5 Asistencia en la operación aduanera</a></li>
                <li><a href="{% url 'Capacitacion' %}">6 Capacitación</a></li>
                <li><a href="{% url 'Estrategias' %}">7 Estrategias comerciales </a></li>
                <li><a href="{% url 'ServiciosC' %}">8 Servicios Corporativas</a></li>
                <li><a href="{% url 'ServiciosD' %}">9 Servicios digitales</a></li>
                <li><a href="{% url 'Alianzas1' %}">10 Alianzas Estrategicas</a>
                <li><a href="{% url 'Alianzas2' %}">10.2 Alianzas Estrategicas</a>
                <li><a href="{% url 'Alianzas3' %}">10.3 Alianzas Estrategicas</a>
                <li><a href="{% url 'Alianzas3' %}">11 Cursos/Capacitaciones</a>
                </li>
              </ul>
            </div>
          </li>
        </ul>
      </nav>
    </header>

    <!-- Banner -->
    <section id="banner">
      <div class="inner">
        <h2>Proyecto de Consultoría</h2>
        <ul class="actions special">
          <br><br>
          <li><a href="{% url 'Conocenos' %}" class="button primary">¿Quiénes somos?</a></li>
          <li><a href="#menu" class="button primary" id="serviciosBtn">Servicios</a></li>
          <li><a href="{% url 'Contacto' %}" class="button primary">Contacto</a></li>
        </ul>
      </div>
    </section>


  <!-- Scripts Albornoz -->
  <script src="{% static 'ConsultoriaApp/js/jquery.min.js'%}"></script>
  <script src="{% static 'ConsultoriaApp/js/jquery.scrollex.min.js'%}"></script>
  <script src="{% static 'ConsultoriaApp/js/jquery.scrolly.min.js'%}"></script>
  <script src="{% static 'ConsultoriaApp/js/browser.min.js'%}"></script>
  <script src="{% static 'ConsultoriaApp/js/breakpoints.min.js'%}"></script>
  <script src="{% static 'ConsultoriaApp/js/util.js'%}"></script>
  <script src="{% static 'ConsultoriaApp/js/main.js'%}"></script>

  <script>
    // Agrega un evento de clic al botón "Capacitación"
    document.querySelector('#menu li:has(> a:contains("Capacitación")) > a').addEventListener('click', function (e) {
      // Detiene la propagación del evento clic para evitar que se cierre el menú
      e.stopPropagation();

      // Muestra u oculta el submenú
      document.querySelector('#menu li:has(> a:contains("Capacitación")) > ul').toggle();
    });
  </script>
</body>

</html>